apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: boneyard-chat-boneyard-assist
  namespace: default
spec:
  alias: boneyard-chat
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: boneyard-chat
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-metal

---
apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: boneyard-embeddings-boneyard-assist
  namespace: default
spec:
  alias: boneyard-embeddings
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: boneyard-embeddings
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-metal

---

apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: boneyard-db-vector-boneyard-assist
  namespace: default
spec:
  alias: boneyard-db-vector
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: boneyard-db-vector
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-metal
