apiVersion: v1
data:
  uri: aHR0cHM6Ly9nZW5haS1wcm94eS5zeXMudGFzLnZtdGFuenUuY29tL3YxLwo=
  api-key: ${GENAI_API_KEY}
  provider: b3BlbmFp  # openai
  type: b3BlbmFp  # openai
kind: Secret
metadata:
  name: genai-creds
type: servicebinding.io/ai