apiVersion: v1
kind: Secret
metadata:
  name: pgvector-creds
type: servicebinding.io/postgresql
data:
  database: cG9zdGdyZXM=
  host: dGNwLnRhcy52bXRhbnp1LmNvbQ==
  password: YzRCNUQzOVg4MGZFZzJuQzZxMTc=
  port: MTAyNg== # 1026
  provider: dGFzcG9zdGdyZXNxbA==  # tas
  type: cG9zdGdyZXNxbAo= # postgresql
  username: cGdhZG1pbg== # pgadmin