spring:
  ai:
    openai:
      api-key: "YOUR KEY"
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: http2

server:
  http2:
    enabled: true
  port: 8443
  #ssl:
  #  enabled: true
  #  key-alias: demo
  #  key-store: classpath:keystore.bks
  #  key-store-password: changeit
  #  key-password: changeit
  #  key-store-type: "BCFKS"

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
#tanzu:
#  governance:
#    fips:
#      exit-on-failure: true