apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-metal
spec:
  content:
    buildTimestamp: "2024-10-14T11:52:17Z"
    gitCommit: 83466808bf791708b4689cb840882a298d99f85f-dirty
    gitURL: github.com/0pens0/spring-metal.git
    packageImage: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:e58145d9666ec88e0b0a8b6e367d300925e6b3a8298e4c03ce3bc6954791e0fc
    packageRefName: spring-metal.apps.local
    packageVersion: 20241014.1152.17055
    summary: git:8346680 @ 2024-10-14T11:52:17Z
    version: 20241014.1152.17055
  health:
    maxUnavailableReplicas: 10%
  image: harbor.vmtanzu.com/openso-tap-apps/spring-metal:20241014.1152.17055@sha256:6918897398065f0382bed0605e23b294c3ce00fb2e9cdec5a4651164a447b9b6
  ports:
  - name: main
    port: 8080
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-metal
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-metal
  - for: kubernetes.service-target
    kind: Service
    name: spring-metal
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-metal-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-metal
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-metal.apps.local.20241014.1152.17055
  - for: kubernetes.delete
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-metal-values
  resources:
    cpu: 300m
    memory: 1Gi
