---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-containerapp-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tanzu-containerapp-installer
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "serviceaccounts", "services"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tanzu-containerapp-installer
subjects:
  - kind: ServiceAccount
    name: tanzu-containerapp-installer
roleRef:
  kind: Role
  name: tanzu-containerapp-installer
  apiGroup: rbac.authorization.k8s.io