apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: spring-metal.apps.local.20240502.0.41848000
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-05-02T17:30:33Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:b3676c128596cda65ca42a6e4b6122b2906b8a0cf4c6c76707da0df8a6409d0e
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240502.0.41848000
