type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: harbor-registry
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iudm10YW56dS5jb20iOnsidXNlcm5hbWUiOiJvcGVuc28iLCJwYXNzd29yZCI6IkF1a2ppbmphYzEhIn19fQ==
kind: Secret
