apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: openso-custom-build-plan
  namespace: default
spec:
  buildpacks:
    builder: tanzu-build-public.packages.broadcom.com/builders/builder-jammy-base:0.1.2@sha256:2370d9e499afb6e0b2fb0d3c4533d733a47f771eb0a115c4f9aa75cd081ee072
  postBuildSteps:
  - namedTask: tanzu-spring-boot
<<<<<<< HEAD:.build/openso-custom-build-plan.yml
  registry: harbor.vmtanzu.com/openso/{name}
=======
  registry: openso/{name}
>>>>>>> c49c2428fe40be08e52320a166136dcbc3b38c7c:.build/custom-build-plan.yaml
  runtimes:
  - description: create a carvel package for deploying on kubernetes
    name: kubernetes-carvel-package
    steps:
    - namedTask: tanzu-kubernetes-deployment
    - namedTask: tanzu-kubernetes-carvel-package
  - description: create kubernetes yaml files for deploying on kubernetes
    name: kubernetes-plain
    steps:
    - namedTask: tanzu-kubernetes-deployment
  - description: write image to file for use with container runtime (i.e docker run)
    name: container-image
    steps:
    - namedTask: tanzu-container-image
