apiVersion: v1
kind: Secret
metadata:
  name: pgvector-aaaa
type: servicebinding.io/postgresql
data:
  database: aaaaaaa
  host: aaaaaaaa
  password: aaaaaaaaa
  port: aaa == # 1026
  provider: aaa  # tas
  type: aaa # postgresql
  username: aaa # pgadmin