apiVersion: v1
data:
  uri: aHR0cHM6Ly9nZW5haS1wcm94eS5zeXMudGFzLnZtdGFuenUuY29tL2VjODRiM2IwLWQzZDQtNGViYi1iMmZhLTg0NGI5MzVmOTI3Ni9vcGVuYWkK
  api-key: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKbGJtUndiMmx1ZENJNkltVmpPRFJpTTJJd0xXUXpaRFF0TkdWaVlpMWlNbVpoTFRnME5HSTVNelZtT1RJM05pSXNJbXRsZVY5cFpDSTZJbUUzWkROa04yUTBMVFE0TnpBdE5EVTVOeTFpT1RRNExXVXpNek5tWmpSaVpEQXpZaUlzSW1Oc2FXVnVkRjlwWkNJNkltUmpOalpsTmpRd0xXVTRZV1l0TkdKa1l5MWlORFkzTFdNelpqSTJNMlV4WkRRNVppSXNJbk4xWWlJNkltWXlOalkxWlRWbExUa3pZV0l0TkRNellTMDVZbUpoTFRBME1UaGxNR013TmpjNU1DSXNJbWxoZENJNk1UY3lPVGN3TmpFNE5YMC5FQWlEdTVwbTVoVUEzTW5kZDl3d3FGVVJWdFZyNTBBRWVoUFV3Zjc0M3ZVCg==
  model-name: Z3B0LTRvCg==
  model-capabilities: Y2hhdCx2aXNpb24K
  provider: dGFuenU= # tanzu
  type: Z2VuYWk=  # genai
kind: Secret
metadata:
  name: boneyard-chat-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: boneyard-chat
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: genai
    secretRef:
      name: boneyard-chat-creds
---
apiVersion: v1
data:
  uri: aHR0cHM6Ly9nZW5haS1wcm94eS5zeXMudGFzLnZtdGFuenUuY29tLzNjMjdmYTg3LTU1YzktNGE5MS04NzNjLTk4ZDFjZTE5ZDZhMS9vcGVuYWkK
  api-key: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKbGJtUndiMmx1ZENJNklqTmpNamRtWVRnM0xUVTFZemt0TkdFNU1TMDROek5qTFRrNFpERmpaVEU1WkRaaE1TSXNJbXRsZVY5cFpDSTZJbVZtTVRZMFlqSmpMVFJrWkRJdE5EZzNOUzFoTjJZeUxXSmlOemd6T0dGa056Vm1ZU0lzSW1Oc2FXVnVkRjlwWkNJNklqTTBOMlF3WkRGaExUVTBORFl0TkRnMU55MDRNemxtTFdVek16RXlPRE13WkRSaU1TSXNJbk4xWWlJNklqZGpPVFpoTkdVNExUUXdOemt0TkdVMU5DMWlORFV6TFRWaE1Ua3laRE0xTkdVd1lTSXNJbWxoZENJNk1UY3lPVGN3TmpFNU1uMC5KcnFPS0ZTSEtkZjNyemhiUjRDQjdWOU4wN214Q2ttblJhUDZnM2N6WTY0Cg==
  model-name: dGV4dC1lbWJlZGRpbmctMy1zbWFsbAo=
  model-capabilities: ZW1iZWRkaW5nCg==
  provider: dGFuenU= # tanzu
  type: Z2VuYWk=  # genai
kind: Secret
metadata:
  name: boneyard-embeddings-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: boneyard-embeddings
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: genai
    secretRef:
      name: boneyard-embeddings-creds
