# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  serviceAccountName: fluxcd-helmrelease-installer
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: '11.3.3'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: grafana-values