apiVersion: v1
data:
  uri: aHR0cHM6Ly9nZW5haS1wcm94eS5zeXMudGFzLnZtdGFuenUuY29tL3Yx
  api-key: <Base64 key>
  provider: b3BlbmFp  # openai
  type: b3BlbmFp  # openai
kind: Secret
metadata:
  name: spring-ai-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: PreProvisionedService
metadata:
  name: gen-ai-service
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: ai
    secretRef: 
      name: spring-ai-creds