apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: pgvector
spec:
  bindingConnectors:
  - name: main
    description: Posgres pgvector service for AI use cases
    type: postgresql
    secretRef:
      name: pgvector-creds