apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-metal
spec:
  content:
    buildTimestamp: "2024-08-14T14:21:10Z"
    gitCommit: 8de8b1c0bc0fd84f846a67f55fb30ed33106425e-dirty
    gitURL: github.com/0pens0/spring-metal.git
    packageImage: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:0d48196aa7367b3d2237f56eaed784957d664f39d2f8c9ce4f875db6d2cc7846
    packageRefName: spring-metal.apps.local
    packageVersion: 20240814.1421.10147
    summary: git:8de8b1c @ 2024-08-14T14:21:10Z
    version: 20240814.1421.10147
  health:
    maxUnavailableReplicas: 10%
  image: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:3147c94ff919a4774c48e3822f99e50309639c8d9c05bd2c58259e3d7c5f7344
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-metal
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-metal
  - for: kubernetes.service-target
    kind: Service
    name: spring-metal
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-metal-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-metal
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-metal.apps.local.20240814.1421.10147
  - for: kubernetes.delete
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-metal-values
  resources:
    cpu: 300m
    memory: 1Gi
