apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
  creationTimestamp: null
  name: spring-metal.apps.local.20240701.1228.1351
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-07-01T12:29:07Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:75e6a1d2e75537a1e225aefc618ac1e74369218bb5b5b09e660266391ae0dfe2
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240701.1228.1351
