apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
  creationTimestamp: null
  name: spring-metal.apps.local.20240925.946.10459
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-09-25T09:47:20Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:5fed6439dbc6a7a3b55b476f0462a4af5b336f20eb28f49ff1d41c7eff4f7074
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240925.946.10459
