apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
  creationTimestamp: null
  name: spring-metal.apps.local.20240722.1056.54929
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-07-22T10:58:07Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: openso.azurecr.io/tap-apps/spring-metal@sha256:0678b1d3264f08ca96377dee6bbce5a7dd67e4cb7bef7da1e0d274996c30bd0d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240722.1056.54929
