name: Deploy gitops project
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "master"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt update
          sudo apt install cf8-cli
          sudo apt install maven -y
          mvn -version


      - name: Connect to CF API
        run: |
          cf api api.sys.vmtanzu.com --skip-ssl-validation
          cf login -u admin -p ${{ secrets.CF_API_TOKEN }} -o tanzu-platform-demo
          cf target -s ${{ secrets.CF_SPACE_NAME }}

      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT: ${{ secrets.API_ENDPOINT || 'console.cloud.vmware.com' }}
        run: |
          #tanzu login --endpoint ${ENDPOINT}
          #tanzu build config --build-plan-source-type=file --build-plan-source platform-config.yml --containerapp-registry harbor.vmtanzu.com/openso-tap-apps/{name}
          #tanzu build config view
          #tanzu context list --wide
          #tanzu project list
          docker login harbor.vmtanzu.com -u openso -p  ${{ secrets.RERGISTRY_PASS}}
          #tanzu project use ${{ secrets.PROJECT_NAME }}
          #tanzu space list
          #tanzu space use ${{ secrets.SPACE_NAME }}
          #tanzu deploy -y --diff
      - run: echo "🍏 This job's status is ${{ job.status }}."
