name: Deploy gitops project
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "master"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt update
          sudo apt install cf8-cli
          sudo apt install maven -y
          mvn -version

      - name: Connect to CF API
        run: |
          cf api https://api.sys.tas.vmtanzu.com --skip-ssl-validation
          cf auth admin ${{ secrets.CF_API_TOKEN }}
          cf target -o tanzu-platform-demo -s spring-metal-space

      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT: ${{ secrets.API_ENDPOINT || 'console.cloud.vmware.com' }}
          REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
          REGISTRY_PASS: ${{ secrets.RERGISTRY_PASS}}
        run: |
          cf target
          docker login ${REGISTRY} -u openso -p  ${REGISTRY_PASS}

      - run: echo "🍏 This job's status is ${{ job.status }}."
