name: Deploy gitops project
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "master"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tanzu CLI
        run: |
          # Install Tanzu CLI and initialize
          TANZU_CLI_VERSION=v1.3.0
          curl -Lo tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-linux-amd64.tar.gz
          curl -Lo tanzu-cli-binaries-checksums.txt https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-binaries-checksums.txt
          
          if [ "$(cat tanzu-cli-binaries-checksums.txt | grep tanzu-cli-linux-amd64.tar.gz)" != "$(sha256sum tanzu-cli-linux-amd64.tar.gz)" ]; then echo "Checksum does not match"; exit 1; fi
          
          tar -xf tanzu-cli-linux-amd64.tar.gz
          mv ${TANZU_CLI_VERSION}/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
          tanzu ceip-participation set false
          tanzu config eula accept
          tanzu init
          tanzu version
      - name: Install deploy and build plugin
        run: |
          # Install Tanzu resource plugin
          # tanzu config set env.TANZU_CLI_ADDITIONAL_PLUGIN_DISCOVERY_IMAGES_TEST_ONLY harbor-repo.vmware.com/tanzu_cli_stage/plugins/plugin-inventory:latest
          # tanzu config set env.TANZU_CLI_PLUGIN_DISCOVERY_IMAGE_SIGNATURE_VERIFICATION_SKIP_LIST harbor-repo.vmware.com/tanzu_cli_stage/plugins/plugin-inventory:latest
          tanzu plugin install --group vmware-tanzu/platform-engineer
          tanzu plugin install --group vmware-tanzu/app-developer
          
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT: ${{ env.API_ENDPOINT || 'console.cloud.vmware.com' }}
        run: |
          tanzu login --endpoint ${ENDPOINT}

          # cd gitops-project
          tanzu build config --build-plan-source-type=file --build-plan-source platform-config.yml --containerapp-registry harbor.vmtanzu.com/openso-tap-apps/{name}
          tanzu build config view
          tanzu context list
          tanzu project list
          tanzu space list

          docker login harbor.vmtanzu.com -u openso -p  ${{ secrets.RERGISTRY_PASS}}
          tanzu project use ${{ env.PROJECT_NAME }}
          tanzu space use ${{ env.SPACE_NAME }}
          tanzu deploy -y --diff
      - run: echo "🍏 This job's status is ${{ job.status }}."
