name: TPK8S Gitops
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "master"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tanzu CLI
        env:
          TANZU_CLI_VERSION: ${{vars.TANZU_CLI_VERSION}}
        run: |
          curl -Lo tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-linux-amd64.tar.gz
          curl -Lo tanzu-cli-binaries-checksums.txt https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-binaries-checksums.txt
          if [ "$(cat tanzu-cli-binaries-checksums.txt | grep tanzu-cli-linux-amd64.tar.gz)" != "$(sha256sum tanzu-cli-linux-amd64.tar.gz)" ]; then echo "Checksum does not match"; exit 1; fi
          tar -xf tanzu-cli-linux-amd64.tar.gz
          mv ${TANZU_CLI_VERSION}/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
          tanzu ceip-participation set false
          tanzu config eula accept
          tanzu init
          tanzu version

      - name: Install tanzu plugins
        run: |
          tanzu plugin install resource

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy resources to Tanzu Project
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT: ${{ vars.API_ENDPOINT || 'console.cloud.vmware.com' }}
        run: |
          tanzu login --endpoint ${ENDPOINT}
          mkdir .secrets
          cd .secrets
          touch pgvector-secret.yml
          touch genai-secret.yml
          echo ${{secrets.GENAI_SECRET}} > genai-secret.yml
          cat genai-secret.yml
          echo ${{secrets.PGVECTOR_SECRET}} > pgvector-secret.yml
          cat pgvector-secret.yml
          cd ../git-ops
          mv ../.secrets/genai-secret.yml spaces/spring-metal-dev
          mv ../.secrets/genai-secret.yml spaces/spring-metal-stage
          mv ../.secrets/pgvector-secret.yml spaces/spring-metal-dev
          mv ../.secrets/pgvector-secret.yml spaces/spring-metal-stage

          tanzu deploy --patch -y

      - run: echo "🍏 This job's status is ${{ job.status }}."
