name: Initial promotion from dev
run-name: ${{ github.actor }} changes
on:
  push: # This Workflow should be added to the repository with application code
    branches:
      - "master"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: install-tanzu-cli
        uses: ./.github/actions/tanzu-cli/
        with:
          version: v1.3.0
      - id: install-tanzu-cli-resource-plugin
        uses: ./.github/actions/tanzu-cli-plugins/
        with:
          name: resource
      - id: install-tanzu-cli-resource-plugin
        uses: ./.github/actions/tanzu-cli-plugins/
        with:
          name: build
      - id: install-tanzu-cli-resource-plugin
        uses: ./.github/actions/tanzu-cli-plugins/
        with:
          name: promote
      - id: login-tanzu
        uses: ./.github/actions/tanzu-login/
        with:
          api-token: ${{ tanzu.API_TOKEN }}
      - name: Build application
        id: build-app
        run: |
          OUTPUT=$(tanzu build)
          echo "buildFolder=${OUTPUT}" >> "$GITHUB_OUTPUT"
      - name: Checkout gitops repository
        uses: actions/checkout@v4
        with:
          repository: 'https://github.com/company/gitops'
          path: gitops-repo
      - name: Promote application
        env:
          APP_NAME: 'spring-metal-gitops'
          PROJECT: ${{ tanzu.PROJECT_NAME }}
          SPACE: ${{ tanzu.SPACE_NAME }}
          OUTPUT: ${{ steps.build-app.outputs.buildFolder }}
        run: |
            cd gitops-repo
            tanzu promote -f $OUTPUT --space $PROJECT/$SPACE
            
            git add -A
            git commit -m "Setup deployment of ${APP_NAME} in $PROJECT/$SPACE"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          path: gitops-repo
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
