name: TPK8S Gitops
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "main"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tanzu CLI
        env:
          TANZU_CLI_VERSION: ${{vars.TANZU_CLI_VERSION}}
        run: |
          curl -Lo tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-linux-amd64.tar.gz
          curl -Lo tanzu-cli-binaries-checksums.txt https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-binaries-checksums.txt
          if [ "$(cat tanzu-cli-binaries-checksums.txt | grep tanzu-cli-linux-amd64.tar.gz)" != "$(sha256sum tanzu-cli-linux-amd64.tar.gz)" ]; then echo "Checksum does not match"; exit 1; fi
          tar -xf tanzu-cli-linux-amd64.tar.gz
          mv ${TANZU_CLI_VERSION}/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
          tanzu ceip-participation set false
          tanzu config eula accept
          tanzu init
          tanzu version

      - name: Install tanzu plugins
        env:
          TANZU_CLI_INCLUDE_DEACTIVATED_PLUGINS_TEST_ONLY: 1
        run: |
          tanzu plugin install resource -v v0.2.1 -t 'global'

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Promote to Prod
        run: |
            cd git-ops/spaces/spring-metal-stage/
            tanzu promote --to ../spring-metal-prod
      
      - name: Deploy resources prod space
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT: ${{ vars.API_ENDPOINT || 'console.cloud.vmware.com' }}
          
        run: |
            tanzu login --endpoint ${ENDPOINT}
            cd git-ops
            tanzu deploy --nested-contexts --patch -y

      - run: echo "🍏 This job's status is ${{ job.status }}."
