apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-metal
spec:
  content:
    buildTimestamp: "2024-07-02T16:39:19Z"
    gitCommit: a3f203285176ddf2cb18b537fcc05931f48ce8ec-dirty
    gitURL: github.com/0pens0/spring-metal.git
    packageRefName: spring-metal.apps.local
    summary: git:a3f2032 @ 2024-07-02T16:39:19Z
    version: 20240702.1639.19205
  image: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:d42e9ba9adfba0edcd71517c329bbf9d4558cca624a80aa4bf724bd87aee41e5
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-metal
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-metal
  - for: kubernetes.service-target
    kind: Service
    name: spring-metal
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-metal-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-metal
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-metal.apps.local.20240702.1639.19205
  - for: kubernetes.delete
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-metal-values
  resources:
    cpu: 300m
    memory: 1Gi
