apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-metal
spec:
  content:
    buildTimestamp: "2024-10-02T22:15:23Z"
    gitCommit: 6464b0ae00b30578046d092c25483f7b746eaf45-dirty
    gitURL: github.com/0pens0/spring-metal.git
    packageImage: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:e8fb345632c9b2b1cd0e3779c00b508c3656b54438e3681f162c9dbdf6f3aced
    packageRefName: spring-metal.apps.local
    packageVersion: 20241002.2215.23401
    summary: git:6464b0a @ 2024-10-02T22:15:23Z
    version: 20241002.2215.23401
  health:
    maxUnavailableReplicas: 10%
  image: harbor.vmtanzu.com/openso-tap-apps/spring-metal:20241002.2215.23401@sha256:1531cf8d21911b5c93ab54d34b0aacf4890ba47c37578c646e03264793685ff8
  ports:
  - name: main
    port: 8080
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-metal
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-metal
  - for: kubernetes.service-target
    kind: Service
    name: spring-metal
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-metal-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-metal
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-metal.apps.local.20241002.2215.23401
  - for: kubernetes.delete
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-metal-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-metal-values
  resources:
    cpu: 300m
    memory: 1Gi
