apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
  creationTimestamp: null
  name: spring-metal.apps.local.20241024.1347.24710
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-10-24T13:48:34Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.vmtanzu.com/openso/spring-metal@sha256:941886c4717699957f87a2d2234e354b5e8bb3e0ba3d8e840a7f42160f743a4f
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241024.1347.24710
