apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
  creationTimestamp: null
  name: spring-metal.apps.local.20240826.1440.38346
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-08-26T15:20:47Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.vmtanzu.com/openso-tap-apps/spring-metal@sha256:cbec5324be2a73b8d70f2523470dcfb440964c6c89b3db4037b6764c7ceeb394
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240826.1440.38346
