apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-metal
  creationTimestamp: null
  name: spring-metal.apps.local.20240722.1100.36952
spec:
  refName: spring-metal.apps.local
  releasedAt: "2024-07-22T11:01:48Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: openso.azurecr.io/tap-apps/spring-metal@sha256:5a05a71426033e15fabae0b33c144587855d0315ec0229887cce1995de94cf52
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240722.1100.36952
